spring:
  application:
    name:OAuth2JWT
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
            client-name: naver
            client-id: y4PeYdJ2tnWhPRh4H1ZZ
            client-secret: 1RbUFYwmmB
        provider:
          naver:
            user-name-attribute: response
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
  jwt:
    secret: 45678u98tejrg98dgu9834uithnoietji0gj0weroginwgagadfsg423jykn:$%^23hg
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/oauth2_jwt
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

